menu:
    日志: /
    归档: /archives/
    实验室: /1000/01/01/实验室/
    微博: http://weibo.com/80yang
    GitHub: https://github.com/windy0220
    Rss: /atom.xml

link:
    'Li Hao': https://lzyb.github.io

favicon: /favicon.png
logo: /avater.png

# Comment
# e.g disqus: seansun
disqus: ma-chen-cn
duoshuo:

# Analytics
# google-analytics:
ga: UA-116335564-1

# Copyright Infomation
startyear: 2015
